#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');const os=require('node:os');
const {collectGraph}=require('./vendor/token-monitor/headless-collector');const {collectQuotas}=require('./quotas');
const {collectCursorUsage}=require('./cursor-usage');
const {applyHermesActual}=require('./hermes-actual');
const AGENTS=['codex','cursor','hermes','workbuddy'];
const nullable=v=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0?v:null;
function dateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function cleanModel(v){return typeof v==='string'&&/^[a-zA-Z0-9_.:/@+ -]{1,96}$/.test(v)&&!v.includes('/Users/')&&!v.includes('/home/')?v:null;}
function normalize(graph,since,until){const rows=new Map();for(const day of graph.contributions||[]){if(!/^\d{4}-\d{2}-\d{2}$/.test(day.date)||day.date<since||day.date>until)continue;for(const c of day.clients||[]){const agent=String(c.client||'').toLowerCase();if(!AGENTS.includes(agent))continue;const model=cleanModel(c.modelId||c.model||c.model_id);const t=c.tokens||{};const components=c.tokenComponentsAvailable!==false;const input=components?nullable(t.input):null,output=components?nullable(t.output):null,cache=components?nullable(t.cacheRead??t.cache_read):null;
// Tokscale synthesizes absent cache-write as 0. Preserve unknown across these sources.
const write=null;const numeric=[nullable(t.input),nullable(t.output),nullable(t.cacheRead??t.cache_read),nullable(t.cacheWrite??t.cache_write)];const total=numeric.every(v=>v!==null)?numeric.reduce((a,b)=>a+b,0):nullable(c.totalTokens??c.total_tokens);
const row={date:day.date,agent,model,input_tokens:input===null||cache===null?null:input+cache+(nullable(t.cacheWrite??t.cache_write)??0),output_tokens:output,cache_read_tokens:cache,cache_write_tokens:write,total_tokens:total,actual_cost:null,coverage:{tokens:total===null?'unknown':'partial',cost:'unknown'},provenance:'tokscale.local_logs',cache_definition:'input includes cache_read and known cache_write; cache fields are input subsets; cache_write availability unknown'};
const key=JSON.stringify([day.date,agent,model]);if(rows.has(key)){const existing=rows.get(key);for(const field of ['input_tokens','output_tokens','cache_read_tokens','cache_write_tokens','total_tokens'])existing[field]=existing[field]===null||row[field]===null?null:existing[field]+row[field];}else rows.set(key,row);
if(rows.size>10000)throw new Error('row_limit');}}
return [...rows.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.agent.localeCompare(b.agent)||(a.model||'').localeCompare(b.model||''));}
function args(){const a=process.argv.slice(2);let root=null,days=30,watch=false;for(let i=0;i<a.length;i++){if(a[i]==='--root')root=a[++i];else if(a[i]==='--days')days=Number(a[++i]);else if(a[i]==='--watch')watch=true;else if(a[i]!=='--once')throw new Error('invalid_argument');}if(!root||!path.isAbsolute(root)||!Number.isInteger(days)||days<1||days>30)throw new Error('invalid_arguments');return{root:path.resolve(root),days,watch};}
async function snapshot(options){const forceQuota=options.forceQuota===true;options.forceQuota=false;const now=new Date(),until=dateKey(now),first=new Date(now);first.setDate(first.getDate()-options.days+1);const since=dateKey(first);let days=[],error=null;try{days=normalize(await collectGraph({root:options.root,since,until}),since,until);}catch(e){error=['row_limit','output_limit','collection_timeout','invalid_collector_json','collector_unavailable','collector_failed'].includes(e.message)?e.message:'collection_failed';}
const cursorUsage=await collectCursorUsage(since,until,forceQuota);days.push(...cursorUsage.days.map(d=>({...d,as_of_ms:cursorUsage.as_of_ms})));
const actualStatus=error?{availability:'unavailable',reason:'collection_failed'}:applyHermesActual(days,since,until);
const sources=AGENTS.map(agent=>({id:agent,agent,availability:error?'unavailable':days.some(d=>d.agent===agent)?'available':'unknown',reason:error||(!days.some(d=>d.agent===agent)?'no_observed_usage':null),coverage:days.some(d=>d.agent===agent)?'partial':'unknown',metric_coverage:{tokens:days.some(d=>d.agent===agent)?'partial':'unknown',cost:agent==='hermes'&&actualStatus.native_rows_applied?'partial':'unknown'},actual_cost_status:agent==='hermes'?actualStatus:{availability:'unknown',reason:'no_native_actual_cost_adapter'},provenance:'tokscale.local_logs',snapshot_complete:error===null}));
const cursorSource=sources.find(s=>s.id==='cursor');Object.assign(cursorSource,{availability:cursorUsage.availability,reason:cursorUsage.reason,snapshot_complete:false,as_of_ms:cursorUsage.as_of_ms,provenance:'cursor.official.usage-events'});
return{version:1,as_of_ms:Date.now(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,range:{since,until},days,sources,quotas:await collectQuotas(forceQuota),errors:error?[{code:error}]:[]};}
async function main(){const options=args();fs.mkdirSync(options.root,{recursive:true,mode:0o700});let running=false,dirty=false,timer=null;async function run(){if(running){dirty=true;return;}running=true;try{const value=await snapshot(options);process.stdout.write(JSON.stringify(value)+'\n');}finally{running=false;if(dirty){dirty=false;changed();}}}await run();if(!options.watch)return;
function changed(){if(timer!==null)return;timer=setTimeout(()=>{timer=null;run();},1500);}
let input='';process.stdin.setEncoding('utf8');process.stdin.on('data',chunk=>{input+=chunk;if(input.length>128){input='';return;}let pos;while((pos=input.indexOf('\n'))>=0){const line=input.slice(0,pos);input=input.slice(pos+1);try{if(JSON.parse(line).action==='refresh'){options.forceQuota=true;changed();}}catch{}}});process.stdin.resume();const home=os.homedir();const roots=[{dir:path.join(process.env.CODEX_HOME||path.join(home,'.codex'),'sessions'),recursive:true},{dir:process.env.HERMES_HOME||path.join(home,'.hermes'),recursive:false,filter:/^state\.db(?:-wal|-shm)?$/},{dir:path.join(home,'Library/Application Support/Cursor/User'),recursive:true,filter:/state\.vscdb(?:-wal|-shm)?$/},{dir:path.join(home,'.workbuddy','projects'),recursive:true}];for(const source of roots){if(!fs.existsSync(source.dir))continue;try{fs.watch(source.dir,{recursive:source.recursive},(_event,filename)=>{if(!source.filter||source.filter.test(String(filename||'')))changed();}).on('error',()=>{});}catch{}}
setInterval(run,300000);}
main().catch(()=>{process.stdout.write(JSON.stringify({version:1,as_of_ms:Date.now(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,days:[],sources:[],quotas:[],errors:[{code:'collector_initialization_failed'}]})+'\n');process.exitCode=1;});
