"""gen_gesture_cases.py — convert acceptance/gesture_cases.json into a C table
consumed by tests/native/test_gesture.c. Single source of truth stays the
JSON fixture; this generated file is committed so native tests build without
Python. Re-run after editing the JSON.

Usage: .venv-doccheck/bin/python tools/gen_gesture_cases.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "Bot_Status_v1_Handoff" / "acceptance" / "gesture_cases.json"
DST = ROOT / "tests" / "native" / "gesture_cases.inc"

EVENT_MAP = {
    "tap": "BOT_GESTURE_TAP",
    "hold": "BOT_GESTURE_HOLD",
    "swipe_left": "BOT_GESTURE_SWIPE_LEFT",
    "swipe_right": "BOT_GESTURE_SWIPE_RIGHT",
    "swipe_up": "BOT_GESTURE_SWIPE_UP",
    "swipe_down": "BOT_GESTURE_SWIPE_DOWN",
    "wake_only": "BOT_GESTURE_WAKE_ONLY",
}
PHASE_MAP = {
    "down": "BOT_TOUCH_DOWN",
    "move": "BOT_TOUCH_MOVE",
    "tick": "BOT_TOUCH_TICK",
    "up": "BOT_TOUCH_UP",
    "cancel": "BOT_TOUCH_CANCEL",
}


def main() -> int:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    cases = data["cases"]

    lines = [
        "/* GENERATED by tools/gen_gesture_cases.py from",
        " * Bot_Status_v1_Handoff/acceptance/gesture_cases.json — do not edit by hand. */",
        "",
    ]
    total_samples = 0
    for case in cases:
        cid = case["id"]
        wake = "true" if case.get("wake_only") else "false"
        samples = case["samples"]
        total_samples += len(samples)
        lines.append(f"static const gesture_sample_t samples_{cid}[] = {{")
        for s in samples:
            lines.append(
                f"    {{ {PHASE_MAP[s['phase']]}, {s['t_ms']}u, {s['x']}, {s['y']} }},"
            )
        lines.append("};")
        expected = case["expected"]
        if expected:
            evs = ", ".join(EVENT_MAP[e] for e in expected)
            lines.append(f"static const bot_gesture_kind_t expected_{cid}[] = {{ {evs} }};")
        else:
            lines.append(f"static const bot_gesture_kind_t expected_{cid}[1] = {{ BOT_GESTURE_NONE }};")
        lines.append("")

    lines.append("static const gesture_case_t GESTURE_CASES[] = {")
    for case in cases:
        cid = case["id"]
        wake = "true" if case.get("wake_only") else "false"
        nexp = len(case["expected"])
        lines.append(
            f'    {{ "{cid}", samples_{cid}, {len(case["samples"])}u, '
            f"expected_{cid}, {nexp}u, {wake} }},"
        )
    lines.append("};")
    lines.append(
        f"static const uint32_t GESTURE_CASE_COUNT = {len(cases)}u; /* samples total: {total_samples} */"
    )
    lines.append("")

    DST.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {DST} ({len(cases)} cases, {total_samples} samples)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
