#!/usr/bin/env python3
"""Render checked-in official artwork with Pillow; no network or installed apps.
See assets/tool-icons/README.md for provenance and SVG rasterization.
"""
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/tool-icons'
NAMES = ('codex', 'workbuddy', 'cursor', 'hermes')  # Firmware agent IDs.

def render(name, size):
    source = Image.open(ASSETS / 'official' / f'{name}.png').convert('RGBA')
    # Preserve full artwork, original colors, aspect ratio, and equal clear space.
    source = ImageOps.contain(source, (size * 5 // 6, size * 5 // 6), Image.Resampling.LANCZOS)
    result = Image.new('RGBA', (size, size), (0, 0, 0, 255))
    result.alpha_composite(source, ((size-source.width)//2, (size-source.height)//2))
    return result.convert('RGB')

def main():
    (ASSETS / 'rendered').mkdir(exist_ok=True)
    lines = ['/* Generated by tools/generate_device_icons.py from official artwork. */', '#include "lvgl.h"']
    for index, name in enumerate(NAMES):
        render(name, 512).save(ASSETS / 'rendered' / f'{name}.png')
        im = render(name, 96)
        im.save(ASSETS / 'rendered' / f'{name}-96.png')
        data = bytearray()
        for r, g, b in im.getdata():
            rgb = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            data.extend((rgb & 255, rgb >> 8))
        lines.append(f'static const uint8_t icon_{index}_data[]={{' + ','.join(map(str, data)) + '};')
        lines.append(f'const lv_image_dsc_t bot_icon_{index}={{.header={{.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.w=96,.h=96,.stride=192}},.data_size=sizeof(icon_{index}_data),.data=icon_{index}_data}};')
    (ROOT / 'firmware/components/bot_ui/assets/icons.c').write_text('\n'.join(lines) + '\n')

if __name__ == '__main__':
    main()
