# Keep the managed BSP immutable. Compile a project-owned derived translation
# unit with bounded internal draw buffers: S3 SPI cannot directly transmit the
# BSP's PSRAM buffers in its current configuration and allocates transient DMA
# copies, which fail after the UI consumes/fragmentates internal RAM.
idf_component_get_property(bot_bsp_dir waveshare__esp32_s3_touch_amoled_1_75 COMPONENT_DIR)
idf_component_get_property(bot_bsp_lib waveshare__esp32_s3_touch_amoled_1_75 COMPONENT_LIB)
set(bot_bsp_source "${bot_bsp_dir}/esp32_s3_touch_amoled_1_75.c")
file(READ "${bot_bsp_source}" bot_bsp_text)
foreach(bot_profile_entry ".buffer_height = 50," ".use_psram = true,")
    string(FIND "${bot_bsp_text}" "${bot_profile_entry}" bot_profile_at)
    if(bot_profile_at EQUAL -1)
        message(FATAL_ERROR "BSP display profile changed; review the bounded DMA buffer adaptation")
    endif()
endforeach()
string(REPLACE ".buffer_height = 50," ".buffer_height = 16," bot_bsp_text "${bot_bsp_text}")
string(REPLACE ".use_psram = true," ".use_psram = false," bot_bsp_text "${bot_bsp_text}")
set(bot_bsp_derived "${CMAKE_BINARY_DIR}/bot_bsp_dma.c")
file(WRITE "${bot_bsp_derived}.in" "${bot_bsp_text}")
configure_file("${bot_bsp_derived}.in" "${bot_bsp_derived}" COPYONLY)
get_target_property(bot_bsp_sources ${bot_bsp_lib} SOURCES)
set(bot_bsp_patched_sources "")
foreach(bot_bsp_item IN LISTS bot_bsp_sources)
    if(bot_bsp_item MATCHES "(^|/)esp32_s3_touch_amoled_1_75\\.c$")
        list(APPEND bot_bsp_patched_sources "${bot_bsp_derived}")
    else()
        list(APPEND bot_bsp_patched_sources "${bot_bsp_item}")
    endif()
endforeach()
set_property(TARGET ${bot_bsp_lib} PROPERTY SOURCES "${bot_bsp_patched_sources}")
